services:
  keycloak-learn-api:
    image: keycloak.api
    container_name: keycloak_learn
    build:
      context: .
      dockerfile: src/Keycloak.Api/Dockerfile
    volumes:
      - ./certificate/development.crt:/etc/ssl/certs/development.crt
      - ./certificate/development.key:/etc/ssl/private/development.key
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/etc/ssl/certs/development.crt
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1q2w3e4R*
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/etc/ssl/private/development.key
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
      - "5001:443"
  
  keycloak-learn-db:
    image: postgres:latest
    container_name: keycloak_learn_db
    environment:
      - POSTGRES_DB=keycloak-learn-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak-learn-idp:
    image: jboss/keycloak:latest
    container_name: keycloak_learn_idp
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 18080:8080