# This is a generated file. Not intended for manual editing.
services:
  keycloak-learn-api:
    build:
      context: "/home/ekrem/RiderProjects/keycloak-learn/keycloak-learn"
      dockerfile: "src/Keycloak.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "/home/ekrem/.nuget/packages"
      NUGET_FALLBACK_PACKAGES: "/home/ekrem/.nuget/packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "keycloak.api:dev"
    ports:
    - "127.0.0.1:57008:57100"
    - "127.0.0.1:57208:57300"
    volumes:
    - "/home/ekrem/.nuget/packages:/root/.nuget/fallbackpackages"
    - "/home/ekrem/RiderProjects/keycloak-learn/keycloak-learn/src/Keycloak.Api:/app:rw"
    - "/home/ekrem/RiderProjects/keycloak-learn/keycloak-learn:/src:rw"
    - "/home/ekrem/.local/share/JetBrains/RiderRemoteDebugger/2023.2.2/Linux64:/riderDebugger"
    - "/home/ekrem/.local/share/JetBrains/Toolbox/apps/rider/bin:/riderLogsConf"
    - "/home/ekrem/.cache/JetBrains/Rider2023.2/log/DebuggerWorker/JetBrains.Debugger.Worker.2023_10_01_15_06_03:/riderLogs:rw"
    working_dir: "/app"
